server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qq?useUnicode=true&characterEncoding=utf8mb4
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 216216
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 
      